### ISSUE TITLE
Installation scripts does not set SKEMA_HOME

### ISSUE THREAD

**Issue by huihzhao** [skema-dev/skemabuild#2]
Received github token: ghoxjklxjklsjfkjitkllafjldsa
panic: SKEMA_HOME not set!

goroutine 1 [running]:
github.com/skema-dev/skema-tool/internal/pkg/io.GetHomePath(...)
	/Users/huizhao/go/pkg/mod/github.com/skema-dev/skema-tool@v0.0.0-20220523054308-f7739b44de85/internal/pkg/io/io.go:43
github.com/skema-dev/skema-tool/internal/auth.(*githubAuth).SaveTokenToFile(0x14000032640)
	/Users/huizhao/go/pkg/mod/github.com/skema-dev/skema-tool@v0.0.0-20220523054308-f7739b44de85/internal/auth/github.go:96 +0x12c
github.com/skema-dev/skema-tool/cmd/st/auth.NewCmd.func1(0x14000142f00?, {0x102cebc39?, 0x0?, 0x0?})
	/Users/huizhao/go/pkg/mod/github.com/skema-dev/skema-tool@v0.0.0-20220523054308-f7739b44de85/cmd/st/auth/auth.go:29 +0x88
github.com/spf13/cobra.(*Command).execute(0x14000142f00, {0x103217f20, 0x0, 0x0})
	/Users/huizhao/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000142c80)
	/Users/huizhao/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/huizhao/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/huizhao/go/pkg/mod/github.com/skema-dev/skema-tool@v0.0.0-20220523054308-f7739b44de85/cmd/st/main.go:19 +0x28

**Comment by likezhang-public** [comment]
fixed.
